note_manager/note/urls.py
from django.urls import path

from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
    filter_list,
    post_publish,
    publish_delete,
)

app_name = 'note'
urlpatterns = [
    path('notes/filters/', filter_list),
    path('', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('<int:id>/', post_detail, name='detail'),
    path('<int:id>/edit/', post_update, name='update'),
    path('<int:id>/delete/', post_delete, name='delete'),
    path('<uuid:unique_id>/', post_publish, name='publish'),
    path('<int:id>/publish_delete', publish_delete, name='publish_delete'),
]

note_manager/note_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include("users.urls", namespace='users')),
    path('note/', include('note.urls', namespace='note')),
    path('admin/', admin.site.urls),
]

note_manager/users/urls.py
from django.urls import path

from .views import (
    user_create,
    login,
    logout,
)

app_name = 'users'
urlpatterns = [
    path('user-create/', user_create, name='user_create'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

note_manager/note/models.py
import uuid

from django.db import models
from django.conf import settings
from django.urls import reverse


class Post(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    uuid_boolean = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=120)
    content = models.TextField()
    favourite = models.BooleanField(default=False)
    CATEGORY_CHOICES = [
        ('LNK', 'Ссылка'),
        ('NT', 'Заметка'),
        ('MEM', 'Памятка'),
        ('TD', 'TO DO'),
        ('ETC', 'Другое'),
    ]
    category = models.CharField(max_length=3, choices=CATEGORY_CHOICES, default='NT')
    created = models.DateField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("note:detail", kwargs={"id": self.pk})

    def get_uuid_url(self):
        return reverse("note:publish", kwargs={"unique_id": self.unique_id})

    class Meta:
        ordering = ["-created", "-updated"]

note_manager/note/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'favourite',
            'category',
        ]

note_manager/note/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.template.context_processors import csrf

from .forms import PostForm
from .models import Post


#  наверно было бы классно еще сделать список опубликованных заметок


def post_create(request):
    if not request.user.is_authenticated:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Заметка успешно создана")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    if instance.user == request.user:
        # проверка на то, доступна ли заметка пользователю (если он ее не создавал, то нельзя показывать)
        context = {
            "title": instance.title,
            "instance": instance,
        }
        return render(request, "post_detail.html", context)
    else:
        raise Http404


def post_list(request):
    if not request.user.is_active:
        return render(request, "post_list.html")
    else:
        context = {}
        # Количество посещений этого представления, полученное из переменной сессии
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1

        context.update(csrf(request))
        fname = request.POST.get('filter')
        sname = request.POST.get('sort')
        query = request.POST.get('query')
        queryset_list = Post.objects.filter(user=request.user)

        catlist = []
        datelist = []
        for obj in queryset_list:
            if obj.category not in catlist:
                catlist.append(obj.category)
        for obj in queryset_list:
            if obj.created not in datelist:
                datelist.append(obj.created)

        if fname:
            if fname == "all":
                queryset_list = queryset_list.all()
            elif fname == "favourite":
                queryset_list = queryset_list.filter(favourite=True)
            elif fname[0] == "c":
                queryset_list = queryset_list.filter(category=fname[1:])
            else:
                queryset_list = queryset_list.filter(created=fname)
        if query:
            queryset_list = queryset_list.filter(Q(title__icontains=query) |
                                                 Q(content__icontains=query)
                                                 ).distinct()
        if sname:
            queryset_list = queryset_list.order_by(sname)

        paginator = Paginator(queryset_list, 10)
        page_request_var = 'page'

        page = request.POST.get(page_request_var)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        context = {
            "query": query,
            "cat_list": catlist,
            "date_list": datelist,
            "object_list": queryset,
            "sort": sname,
            "filter": fname,
            "page_request_var": page_request_var,
            'num_visits': num_visits
        }
        return render(request, "post_list.html", context)


def post_update(request, id=None):
    if not request.user.is_authenticated:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None,
                    request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Заметка успешно сохранена")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, id=None):
    if not request.user.is_authenticated:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "Заметка успешно удалена")
    return redirect("note:list")


def filter_list(request):
    context = {}
    context.update(csrf(request))
    fname = request.POST.get('filter')
    sname = request.POST.get('sort')
    query = request.POST.get('query')
    queryset_list = Post.objects.filter(user=request.user)

    if fname:
        if fname == "all":
            queryset_list = queryset_list.all()
        elif fname == "favourite":
            queryset_list = queryset_list.filter(favourite=True)
        elif fname[0] == "c":
            queryset_list = queryset_list.filter(category=fname[1:])
        else:
            queryset_list = queryset_list.filter(created=fname)
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query) |
                                             Q(content__icontains=query)
                                             ).distinct()
    if sname:
        queryset_list = queryset_list.order_by(sname)

    paginator = Paginator(queryset_list, 10)
    page_request_var = 'page'

    page = request.POST.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "page_request_var": page_request_var
    }
    return render(request, "filter_list.html", context)


def post_publish(request, unique_id):
    if not request.user.is_authenticated:
        raise Http404
    instance = get_object_or_404(Post, unique_id=unique_id)
    if instance.uuid_boolean == 0:
        instance.uuid_boolean = 1
        instance.save()
        messages.success(request, "Заметка успешно опубликована")
    context = {
        "instance": instance
    }
    template = loader.get_template('note_static.html')
    return HttpResponse(template.render(context, request))


def publish_delete(request, id=None):
    if not request.user.is_authenticated:
        raise Http404
    instance = get_object_or_404(Post, id=id)
    instance.uuid_boolean = 0
    instance.save()
    messages.success(request, "Публикация успешно удалена")
    return HttpResponseRedirect(instance.get_absolute_url())

note_manager/note/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Менеджер заметок{% endblock head_title %}</title>
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href='{% static "note/base.css" %}'/>
    <script src='{% static "js/jquery-3.4.1.min.js" %}' type="text/javascript"></script>
    <script src='{% static "js/filters.js" %}' type="text/javascript"></script>
    <style>
    {% block style %}{% endblock style %}
    </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'note:list' %}">Мои заметки</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% if user.is_active %}
            {% if user.is_authenticated %}
                <li><a href="{% url 'note:create' %}">Добавить заметку</a></li>
            {% endif %}
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_active %}
            <li> <a href="{% url 'users:logout' %}">Выход ({{ user.username }})</a></li>
        {% else %}
            {% if "auth/" not in request.get_full_path %}
                <li> <a href="{% url 'users:login' %}">Вход</a></li>
                <li> <a href="{% url 'users:user_create' %}">Регистрация</a></li>
            {% endif %}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<br><br><br><br>

{% block user_create %}{% endblock user_create %}
{% block login %}{% endblock login %}

<div class="container">
    {% include "messages_display.html" %}

    {% if user.is_authenticated %}
        {% block content %}{% endblock content %}
    {% else %}

    <div class="col-sm-12">
        <p>Войдите или зарегистрируйтесь, чтобы увидеть свои заметки.</p>
    </div>
    
    {% endif %}

</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

</body>
</html>

note_manager/note/templates/filter_list.html
      {% if object_list|length > 0 %}

        {% for obj in object_list %}

          <div class="row">
            <div class="col-sm-12">
              <div class="thumbnail">
                <div class="caption">
                  <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h3>
                  <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
                  <small>{{ obj.created }}</small>
                  <p>Категория: {{ obj.get_category_display }}</p>
                  {% if obj.favourite %}
                    <p>Избранное</p>
                  {% endif %}
                </div>
              </div>
            </div>
            <hr/>
          </div>

        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.POST.query %}&query={{ request.POST.query }}{% endif %}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>

                {% if object_list.has_next %}
                    <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.POST.query %}&query={{ request.POST.query }}{% endif %}">next</a>
                {% endif %}
            </span>
        </div>
      {% else %}
        <p>Заметки не найдены</p>
      {% endif %}

note_manager/note/templates/messages_display.html
{% if messages %}
    <div class="message">
	    <ul class="messages">
        	{% for message in messages %}
        		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        	{% endfor %}
    	</ul>
    </div>
{% endif %}

note_manager/note/templates/note_static.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body>
<div class="col-sm-6 col-sm-offset-3">

	<h1>{{ instance.title }}</h1><br>
	<h3>{{ instance.content }}</h3><br>
	<small>Создано: {{ instance.created }}</small>
	<p>Категория: {{ instance.category }}</p>

	{% if instance.favourite %}
		<p>Избранное</p><br>
	{% endif %}
	<input type="button" onclick="history.back();" value="Вернуться"/>

</div>
</body>
</html>

note_manager/note/templates/post_detail.html
{% extends "base.html" %}

{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}


{% block content %}

<div class="col-sm-6 col-sm-offset-3">

	<h1>{{ title }}</h1><br>
	<h3>{{ instance.content }}</h3><br>
	{% if instance.uuid_boolean %}
	<a href="{% url 'note:publish' instance.unique_id %}">Доступна по ссылке</a><br>
	{% endif %}
	<small>Создано: {{ instance.created }}</small>
	<p>Категория: {{ instance.get_category_display }}</p>

	{% if instance.favourite %}
		<p>Избранное</p><br>
	{% endif %}
	<a href="{{ instance.get_absolute_url }}edit">Изменить</a>
	<a href="{{ instance.get_absolute_url }}delete">Удалить</a>
	{% if instance.uuid_boolean %}
	<a href="{% url 'note:publish_delete' instance.id %}">Отменить публикацию</a>
	{% else %}
	<a href="{{ instance.get_uuid_url }}">Опубликовать</a>
	{% endif %}

</div>

{% endblock content %}

note_manager/note/templates/post_form.html
{% extends "base.html" %}

{% block content %}

<h1>Новая заметка</h1>

<form method="POST", action="", enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit", class="btn btn-default", value="Сохранить"/>
</form>

{% endblock content %}

note_manager/note/templates/post_list.html
{% extends "base.html" %}

{% block content %}



    <form method="POST" name="get_form" action="">
    {% csrf_token %}
      <div class="sidebar-nav-fixed affix">
        <div class="well">

          <select name="sort", id="sort">
            <option value="-created">Дата(по убыванию)</option>
            <option value="created">Дата(по возрастанию)</option>
            <option value="-favourite">Избранное</option>
            <option value="category">Категории</option>
          </select>
          <br><br>

          <select name="filter", id="filter">
            <option value="all">Все</option>
            <option value="favourite">Избранное</option>
            {% for obj in cat_list %}
              <option value="c{{ obj }}">{{ obj }}</option>
            {% endfor %}
            {% for obj in date_list %}
              <option value="{{ obj|date:"Y-m-d" }}">{{ obj }}</option>
            {% endfor %}
          </select>
          <br><br>

          <input type="text" name="query" id="query" placeholder="Поиск заметки"/>
        
        </div>
      </div>
    

    <div id="list" class="col-sm-6 col-sm-offset-3">
      {% include "filter_list.html" %}
      

    </div>
    {% if user.is_authenticated %}
        <footer>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}</footer>
    {% endif %}
    </form>

{% endblock content %}